/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SubmitAnswerTextWithImagesRequestImagesInner {
    /**
     * Base64-encoded image data.
     */
    'data': string;
    /**
     * Image MIME type.
     */
    'media_type': SubmitAnswerTextWithImagesRequestImagesInnerMediaTypeEnum;
}

export const SubmitAnswerTextWithImagesRequestImagesInnerMediaTypeEnum = {
    PNG: 'image/png',
    JPEG: 'image/jpeg',
    GIF: 'image/gif',
    WEBP: 'image/webp',
    HEIC: 'image/heic'
} as const;

export type SubmitAnswerTextWithImagesRequestImagesInnerMediaTypeEnum = typeof SubmitAnswerTextWithImagesRequestImagesInnerMediaTypeEnum[keyof typeof SubmitAnswerTextWithImagesRequestImagesInnerMediaTypeEnum];

export interface SubmitAnswerTextWithImagesRequest {
    /**
     * Freeform text answer with image attachments.
     */
    'kind': SubmitAnswerTextWithImagesRequestKindEnum;
    /**
     * Freeform answer text (required when submitting images).
     */
    'text': string;
    /**
     * Array of image attachments (1-4 images, each <= 5 MB).
     */
    'images': Array<SubmitAnswerTextWithImagesRequestImagesInner>;
}

export const SubmitAnswerTextWithImagesRequestKindEnum = {
    TEXT_WITH_IMAGES: 'text_with_images'
} as const;

export type SubmitAnswerTextWithImagesRequestKindEnum = typeof SubmitAnswerTextWithImagesRequestKindEnum[keyof typeof SubmitAnswerTextWithImagesRequestKindEnum];
